version: '3.8'

name: reiverr

services:
  reiverr:
    image: ghcr.io/just5ky/reiverr:master
    container_name: reiverr
    ports:
      - 9494:9494
    volumes:
      - ${APP_DATA_DIR}/config:/config
    restart: unless-stopped
