version: '3.8'
services:
  app_proxy:
    environment:
      APP_HOST: reiverr_server_1
      APP_PORT: 9494
      PROXY_AUTH_ADD: 'false'
  server:
    image: >
      ghcr.io/aleksilassila/reiverr:latest
    volumes:
      - ${APP_DATA_DIR}/config:/config
    restart: unless-stopped
    container_name: reiverr

